/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // RestAssured for API testing
    testImplementation("io.rest-assured:rest-assured:5.3.0")

    // JUnit for testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")

    // JSONPath support for RestAssured (optional, but useful for JSON assertions)
    testImplementation("io.rest-assured:json-path:5.3.0")

    // Hamcrest matchers (already used in your test)
    testImplementation("org.hamcrest:hamcrest:2.2")

    // Selenium for UI testing - ¡AGREGA ESTAS DEPENDENCIAS!
    testImplementation("org.seleniumhq.selenium:selenium-java:4.39.0")
    testImplementation("org.seleniumhq.selenium:selenium-chrome-driver:4.39.0")
    
    // WebDriverManager para manejar automáticamente los drivers
    testImplementation("io.github.bonigarcia:webdrivermanager:5.6.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
